[project]
name = "skeleton-tracking"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "antoj2", email = "antonfurbojensen@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "mediapipe==0.10.9",
    "opencv-python>=5.0.0.93",
]

[project.scripts]
skeleton-tracking = "skeleton_tracking:main"

[build-system]
requires = ["uv_build>=0.12.19,<0.13.0"]
build-backend = "uv_build"

